### ISSUE TITLE
components/Switch module is missing

### ISSUE THREAD

**Issue by hasangursoy** [JSLancerTeam/crystal-dashboard#10]
Failed to compile.

./src/pages/Forms/ExtendedForms/Switches.js
Module not found: Can't resolve 'components/Switch' in '\crystal-dashboard-master\src\pages\Forms\ExtendedForms'

**Comment by rafzei** [comment]
@hasangursoy got the same but not only in Switches.js. Looks like there is missing variable NODE_PATH eg. add in .env: 
`NODE_PATH=./src`
