### ISSUE TITLE
Issue while running on prod mode

### ISSUE THREAD

**Issue by askshripad** [JSLancerTeam/crystal-dashboard#11]
Hi,

I am getting below issues while running on production mode. Basically, I am running client from node js server. I ma using Node JS version 10.15.
**Uncaught SyntaxError: Unexpected token <
manifest.json:1 Manifest: Line: 1, column: 1, Unexpected token.**

Can you please help.

Thank you,
Shripad

**Comment by askshripad** [comment]
I could able to fix the issue. Fix is we need to change the "homepage" link in package.json.
 In my case, I set to http://localhost:5000. I did not get the reason but it worked.

**Comment by tarifrudrapur** [comment]
Remove `homepage` line from `package.json` should work.

**Comment by davidtran** [comment]
@askshripad does it work for you?

**Comment by askshripad** [comment]
Yes, it worked for me. Thank you :)
