### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by ABHISHEK-ANGADI25** [JSLancerTeam/crystal-dashboard#19]
Hi Brother,

Brother, can you help me to create login page for this dashboard. because I'm beginner in react-redux, and i tried login page but, its not routing to main dashboard after clicking the login button, please help me. Thank you....

**Comment by djkamry22** [comment]
Hello brother!
Have you already dealt with this code?
Could you tell me where to change the color of the sidebar?

**Comment by davidtran** [comment]
Please take a look at the document: https://reacttraining.com/react-router/web/guides/quick-start
