### ISSUE TITLE
Bug: Compile error

### ISSUE THREAD

**Issue by jessethach** [JSLancerTeam/crystal-dashboard#2]
Receiving a compile error on  Node v8.9.1:

```
Failed to compile.

./src/index.js
Module not found: Can't resolve 'sweetalert/dist/sweetalert.css' in '/Users/${user}/dashboards/v1/crystal-dashboard/src'
```

I am not seeing where 'sweetalert/dist/' is coming from. It compiles if I comment out the code, but the Sweetalert features are not styled. Any idea what could be going on?

**Comment by davidtran** [comment]
Thanks, I am checking this bug.

**Comment by davidtran** [comment]
sweetalert dependency is added to package.json
