### ISSUE TITLE
Possible bug in side bar

### ISSUE THREAD

**Issue by lpbaiser** [JSLancerTeam/crystal-dashboard#4]
I'm using this dashboard in my project, so I programming my pages and components. But I think that occurred this bug in side bar component. I think so this problem is scss code, because I removed the 'div' class and the problem has slightly improved. But that did not solve. Can you help me?

![screen shot 2018-02-12 at 00 11 56](https://user-images.githubusercontent.com/14255595/36081786-a88fb4f8-0f8a-11e8-97a2-8012ebdb0ab7.png)

**Comment by BugKiller-tech** [comment]
I have met same issue.
I used this in my project before 1 month and that worked fine before.
but now I need to add some features, so I opened project and tried to run.
I met this issue. Please help me!

**Comment by lpbaiser** [comment]
@RoraxHan I fixed the bug and create a pull request here. 

But you can fix in your project, follow the steps:
1. go to index.html file
2. find this line: `https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css`
3. change by: `https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css`
this must be fix bug.
