### ISSUE TITLE
Sidebar is messy

### ISSUE THREAD

**Issue by BugKiller-tech** [JSLancerTeam/crystal-dashboard#5]
I met this problem nowadays. in the previous all was good.
but now sidebar is messy in my case.
and even your demo site also have the same problem

[https://jslancerteam.github.io/crystal-dashboard/#/](https://jslancerteam.github.io/crystal-dashboard/#/)

I love this dashboard. please guide me to fix this issue.
Thank you!

**Comment by lpbaiser** [comment]
@RoraxHan  look to #4

**Comment by davidtran** [comment]
fixed by @lpbaiser
