### ISSUE TITLE
'NODE_PATH' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by blpraveen** [JSLancerTeam/crystal-dashboard#9]
> NODE_PATH=./src node scripts/start.js

'NODE_PATH' is not recognized as an internal or external command,
operable program or batch file.

**Comment by davidtran** [comment]
Are you using Windows ?

**Comment by trungna1374** [comment]
I have same issue on windows.

**Comment by davidtran** [comment]
This is a popular issue on window. Could you try run this command:
```
npm install -g cross-env
```
Please let me know if it fix issue.

**Comment by trungna1374** [comment]
thanks for your help. But i still can't run. And i have already try another
UI.

Vào Th 2, 1 thg 10, 2018 vào lúc 16:16 David Tran <
notifications@github.com> đã viết:

**Comment by canertosuner** [comment]
same issue +1

**Comment by si62** [comment]
I modify package.json scripts:
.....
"scripts": {
    "setpath":"set NODE_PATH=./src",
    "start": "npm run -s setpath & node scripts/start.js",
    "build": "npm run -s setpath & node scripts/build.js",
    "test": "npm run -s setpath & node scripts/test.js --env=jsdom",
.....

**Comment by hasangursoy** [comment]
You can update following in package.json:

"start": "node scripts/start.js"

**Comment by simonkaspersen** [comment]
On Windows you can edit the scripts in `packages.json` and replace `NODE_PATH=./src` with `$env:NODE_PATH='./src' `

**Comment by MURUGENTHIRAN** [comment]
I got same issues 
after update this comments:
             "scripts": {
"setpath":"set NODE_PATH=./src",
"start": "npm run -s setpath & node scripts/start.js",
"build": "npm run -s setpath & node scripts/build.js",
"test": "npm run -s setpath & node scripts/test.js --env=jsdom",
}


 Failed at the crystal-dashboard@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by kordanian** [comment]
There are all sorts of file path problems so npm start doesn't work.  I tried to push a branch with all the path fixes but I don't have permission.

**Comment by dk432664** [comment]
> > NODE_PATH=./src node scripts/start.js
> 
> 'NODE_PATH' is not recognized as an internal or external command,
> operable program or batch file.

I have the same problem....please help

**Comment by dk432664** [comment]
> I modify package.json scripts:
> .....
> "scripts": {
> "setpath":"set NODE_PATH=./src",
> "start": "npm run -s setpath & node scripts/start.js",
> "build": "npm run -s setpath & node scripts/build.js",
> "test": "npm run -s setpath & node scripts/test.js --env=jsdom",
> .....

After doing this ...it is giving this problem

Cannot destructure property `compile` of 'undefined' or 'null'.

**Comment by davidtran** [comment]
I just added cross-env. It should fix the NODE_PATH issue on window.
